# 101 문제

https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.20.3


In [15]:
# array_1d = np.array([0,1,2,3,4,5,6,7,8,9])
array_1d = np.arange(10)
print(type(array_1d))
print(array_1d)
print(array_1d.shape)

print(type(array_1d.shape))

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
(10,)
<class 'tuple'>


In [16]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [37]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(out)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [42]:
np.arange(10).reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [48]:
 np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])